create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  github_login text,
  github_avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_days (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  day date not null,
  learn jsonb not null default '[]'::jsonb,
  revise jsonb not null default '[]'::jsonb,
  build jsonb not null default '[]'::jsonb,
  problem jsonb not null default '[]'::jsonb,
  tip text not null default '',
  phase text not null default '',
  completions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, day)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists schedule_days_set_updated_at on public.schedule_days;
create trigger schedule_days_set_updated_at
before update on public.schedule_days
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.schedule_days enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
using (auth.uid() is not null and auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
with check (auth.uid() is not null and auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
using (auth.uid() is not null and auth.uid() = id)
with check (auth.uid() is not null and auth.uid() = id);

drop policy if exists "Users can read own schedule" on public.schedule_days;
create policy "Users can read own schedule"
on public.schedule_days
for select
using (auth.uid() is not null and auth.uid() = user_id);

drop policy if exists "Users can insert own schedule" on public.schedule_days;
create policy "Users can insert own schedule"
on public.schedule_days
for insert
with check (auth.uid() is not null and auth.uid() = user_id);

drop policy if exists "Users can update own schedule" on public.schedule_days;
create policy "Users can update own schedule"
on public.schedule_days
for update
using (auth.uid() is not null and auth.uid() = user_id)
with check (auth.uid() is not null and auth.uid() = user_id);

drop policy if exists "Users can delete own schedule" on public.schedule_days;
create policy "Users can delete own schedule"
on public.schedule_days
for delete
using (auth.uid() is not null and auth.uid() = user_id);
